from packages.domain_constants.cause_categories import CauseCategoryEnum
from data.error_code_samples import ERROR_CODE_POOLS

# Flatten the ERROR_CODE_POOLS from Phase 2 into a fast O(1) lookup dictionary.
# Every code generated by Phase 2 should resolve here.
RULES: dict[str, CauseCategoryEnum] = {}

for cause_str, codes in ERROR_CODE_POOLS.items():
    cause_enum = CauseCategoryEnum(cause_str)
    for code in codes:
        RULES[code] = cause_enum
